import { RepoSummary } from "@/lib/api";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Separator } from "@/components/ui/separator";
import { Button } from "@/components/ui/button";
import { Sparkles } from "lucide-react";

interface SummaryPanelProps {
    summary: RepoSummary | null;
    onGenerate: () => void;
    loading: boolean;
}

export function SummaryPanel({ summary, onGenerate, loading }: SummaryPanelProps) {
    if (!summary) {
        return (
            <Card className="h-full flex flex-col items-center justify-center p-6 text-center">
                <div className="bg-teal-500/10 p-4 rounded-xl mb-4">
                    <Sparkles className="h-8 w-8 text-teal-400" />
                </div>
                <h3 className="text-lg font-semibold mb-2">AI Onboarding Assistant</h3>
                <p className="text-muted-foreground mb-4">
                    Generate a comprehensive summary, tech stack analysis, and onboarding guide using Gemini.
                </p>
                <Button onClick={onGenerate} disabled={loading} className="bg-teal-500 hover:bg-teal-600 text-black">
                    {loading ? "Generating..." : "Generate Summary"}
                </Button>
            </Card>
        );
    }

    return (
        <Card className="h-full flex flex-col">
            <CardHeader>
                <CardTitle className="flex items-center gap-2">
                    <Sparkles className="h-5 w-5 text-teal-400" />
                    AI Summary
                </CardTitle>
                <CardDescription>Generated by Gemini</CardDescription>
            </CardHeader>
            <CardContent className="flex-1 min-h-0 p-0">
                <ScrollArea className="h-full px-6 pb-6">
                    <div className="space-y-6 pt-6">
                        <div>
                            <h4 className="font-semibold text-lg mb-2">Overview</h4>
                            <p className="text-sm text-muted-foreground leading-relaxed">{summary.summary}</p>
                        </div>

                        <Separator />

                        <div>
                            <h4 className="font-semibold text-lg mb-2">Tech Stack</h4>
                            <div className="flex flex-wrap gap-2">
                                {summary.tech_stack.map((tech) => (
                                    <span key={tech} className="px-2 py-1 bg-teal-500/10 text-teal-400 rounded-md text-xs font-medium border border-teal-500/20">
                                        {tech}
                                    </span>
                                ))}
                            </div>
                        </div>

                        <Separator />

                        <div>
                            <h4 className="font-semibold text-lg mb-2">Key Components</h4>
                            <ul className="list-disc list-inside text-sm text-muted-foreground space-y-1">
                                {summary.key_components.map((item, i) => (
                                    <li key={i}>{item}</li>
                                ))}
                            </ul>
                        </div>

                        <Separator />

                        <div>
                            <h4 className="font-semibold text-lg mb-2">Entry Points</h4>
                            <ul className="space-y-1">
                                {summary.entry_points.map((ep, i) => (
                                    <li key={i} className="text-sm font-mono bg-slate-100 dark:bg-slate-800 p-1 rounded px-2 w-fit">
                                        {ep}
                                    </li>
                                ))}
                            </ul>
                        </div>

                        <Separator />

                        <div>
                            <h4 className="font-semibold text-lg mb-2">Onboarding Guide</h4>
                            <ol className="list-decimal list-inside text-sm text-muted-foreground space-y-2">
                                {summary.onboarding_steps.map((step, i) => (
                                    <li key={i} className="pl-1">{step}</li>
                                ))}
                            </ol>
                        </div>
                    </div>
                </ScrollArea>
            </CardContent>
        </Card>
    );
}
